FROM tomcat:latest 

RUN cp -R /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps/

# Copy the WAR file to Tomcat webapps directory
COPY target/ABCtechnologies-1.0.war /usr/local/tomcat/webapps/

# Expose port 8080
EXPOSE 8080

# Start Tomcat server
CMD ["catalina.sh", "run"]
