apiVersion: v1
kind: Service
metadata:
  name: abctechnologies-service
  namespace: abctech
  labels:
    app: abctechnologies
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: abctechnologies
---
apiVersion: v1
kind: Service
metadata:
  name: abctechnologies-nodeport
  namespace: abctech
  labels:
    app: abctechnologies
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: abctechnologies
