---
- name: Build and push Docker image
  hosts: docker-server
  become: yes
  vars:
    dockerhub_username: "{{ dockerhub_username }}"
    dockerhub_password: "{{ dockerhub_password }}"
    image_name: "{{ dockerhub_username }}/abc-tomcat-app:latest"
    war_source: /var/lib/jenkins/workspace/Task4-CICD-Deploy-with-Ansible/target/ABCtechnologies-1.0.war
    build_dir: /tmp/docker_build
    dockerfile_src: "{{ playbook_dir }}/../../Dockerfile"
    k8s_manifest: "{{ playbook_dir }}/../../k8s/deployment.yaml"
  tasks:
    - name: Ensure build directory exists
      file:
        path: "{{ build_dir }}"
        state: directory

    - name: Copy WAR file to build directory
      copy:
        src: "{{ war_source }}"
        dest: "{{ build_dir }}/abc.war"

    - name: Copy Dockerfile to build directory
      copy:
        src: "{{ dockerfile_src }}"
        dest: "{{ build_dir }}/Dockerfile"
        remote_src: false

    - name: List contents of build directory
      ansible.builtin.shell: ls -l {{ build_dir }}
      register: build_dir_contents

    - name: Show build directory contents
      debug:
        var: build_dir_contents.stdout_lines

    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: "{{ build_dir }}"
        name: "{{ image_name }}"
        push: no

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        push: yes

    - name: Copy Kubernetes manifest to local
      fetch:
        src: "{{ k8s_manifest }}"
        dest: /tmp/deployment.yaml
        flat: yes

- name: Deploy to Kubernetes
  hosts: k8s-master
  become: yes
  tasks:
    - name: Copy Kubernetes manifest to k8s-master
      copy:
        src: /tmp/deployment.yaml
        dest: /tmp/deployment.yaml
        remote_src: no

    - name: Deploy to Kubernetes
      kubernetes.core.k8s:
        state: present
        src: /tmp/deployment.yaml
