global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape node-exporter metrics
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "172.31.20.154:9100"  # docker-host
          - "172.31.17.179:9100"  # Tomcat-server
          - "172.31.18.103:9100"  # ansibe-host
          - "172.31.19.183:9100"  # kubernetes-cluster
          - "172.31.29.239:9100"  # monitoring
          - "172.31.23.250:9100"  # jenkins-server

  # Scrape cAdvisor metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Scrape Docker daemon metrics (if configured)
  - job_name: "docker-daemon"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Application metrics (if your Java app exposes metrics)
  - job_name: "java-app"
    static_configs:
      - targets: ["host.docker.internal:8081"]  # Adjust port as needed
    scrape_interval: 30s
    metrics_path: /actuator/prometheus  # Spring Boot actuator endpoint

  # Jenkins metrics (if Jenkins exposes metrics)
  - job_name: "jenkins"
    static_configs:
      - targets: ["host.docker.internal:8080"]  # Jenkins default port
    scrape_interval: 60s
    metrics_path: /prometheus/
